### PR TITLE
Update pybind11

### PR DESCRIPTION
**Pull request by stuarteberg**
I want that sweet, sweet support for [`py::call_guard`](http://pybind11.readthedocs.io/en/stable/advanced/functions.html#call-guard).

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks `2.2.0` actually had a bug that prevented us from migrating to the `2.2` series.

Could you leave the older xtl version requirements for this PR? We are following `semver` for versioning.

Note that you cannot use the stable release of `xtensor-python` with `xtensor` master. We are preparing a major release for early next week that has a breaking change impacting the language bindings which will need new releases (xtensor-r, xtensor-julia and xtensor-python).

**Comment by stuarteberg** [comment]
>Could you leave the older xtl version requirements for this PR?

Happy to revert the change, of course, but wasn't the original requirement text a typo?  The latest of `xtl` is `0.3.1`.  The old requirement allows everything up to `0.12.99`!  Are you just planning very far ahead into the future? 😉

**Comment by SylvainCorlay** [comment]
Right, this should have been `<0.3`, I did not catch the typo!

**Comment by stuarteberg** [comment]
OK, I amended the PR.  Now it says `xtl >=0.2.8,<0.3`.

**Comment by stuarteberg** [comment]
PS -- thanks for the tip about compatibility with `xtensor` master.

**Pull request merged**
